# data
input_size: [384, 512]
video_path: 'data/demo.mp4'

# model
N: 256
T: 24
stride: 4
num_layers: 3
embed_dim: 256
num_heads: 4
num_levels: 4
num_neighbors: 9
top_k_regions: 9
dropout: 0.1
memory_size: 12
spa_corr_thre: 1000
add_spatial_penalty: true

lambda_cls: 3.0
lambda_vis: 1.0
lambda_off: 1.0
lambda_unc: 1.0
lambda_ref: 1.0
loss_after_query: true
checkpoint_path: 'checkpoints/lbm.pt'
detector_checkpoint_path: 'checkpoints/yoloe-11l-seg.pt'

# track
object_points: 20
prompt: 'bird'
detect_every_n_frame: 1
detect_threshold: 0.01
init_score_thr: 0.1
obj_score_thr: 0.1
match_score_thr: 0.1
memo_tracklet_frames: 30
memo_point_frames: 3
distractor_score_thr: 0.5
distractor_nms_thr: 0.3
rm_distractor: true
max_distance: 100.0
fps: 30
weight_match_with_det_scores: true
weight_match_with_det_labels: true