# === Data settings ===
train_root: data/kubric_lbm
val_root: data/tapvid_davis/tapvid_davis.pkl
eval_dataset: davis  # choices: [davis, kinetics, robotap, bft, tao, ovt-b]
augmentation: true
input_size: [384, 512]
model_save_path: lbm
vis_save_path: null
checkpoint_path: null # for resume training or evaluation
seed: 42
N: 256
T: 24

# === Model settings ===
stride: 4
num_layers: 3
embed_dim: 256
num_heads: 4
num_levels: 4
num_neighbors: 9
top_k_regions: 9
dropout: 0.1
random_memory_mask_drop: 0.1
memory_size: 12  # for training

# === Training settings ===
epoch_num: 150
lr: 0.0005 # 5e-4
wd: 0.00001 # 1e-5
bs: 4  # Batch size per GPU
amp: true
loss_after_query: true
lambda_cls: 3.0  # Classification CE loss
lambda_vis: 1.0  # Visibility CE loss
lambda_reg: 1.0  # Offset prediction L1 loss
lambda_unc: 1.0  # Uncertainty CE loss
lambda_ref: 1.0  # Reference point uncertainty CE loss

# === Eval Settings ===
validation: false
val_memory_size: 48
val_vis_delta: 0.8
dataset_settings:
  davis:
    val_memory_size: 20
    val_vis_delta: 0.8
  robotap:
    val_memory_size: 60
    val_vis_delta: 0.8
  kinetics:
    val_memory_size: 36
    val_vis_delta: 0.8